[package]
name = "auction-mock"
version = "0.3.4"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[features]
wasm-output-mode = [
    "elrond-wasm-node",
]

[dependencies.node-storage]
path = "../node-storage"

[dependencies.elrond-wasm]
version = "0.17.2"

[dependencies.elrond-wasm-derive]
version = "0.17.2"

[dependencies.elrond-wasm-node]
version = "0.17.2"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.17.2"
