[package]
name = "auction-mock"
version = "0.3.4"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[dependencies.node-storage]
path = "../node-storage"

[dependencies.elrond-wasm]
version = "0.28.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.28.0"
