[package]
name = "auction-mock"
version = "0.3.4"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[dependencies]
node-storage = { path = "../node-storage" }

elrond-wasm = "0.6.1"
elrond-wasm-node = "0.6.1"
elrond-wasm-derive = "0.6.1"

# elrond-wasm = { path = "../../elrond-wasm-rs/elrond-wasm" }
# elrond-wasm-node = { path = "../../elrond-wasm-rs/elrond-wasm-node" }
# elrond-wasm-derive = { path = "../../elrond-wasm-rs/elrond-wasm-derive" }
