[package]
name = "auction-mock"
version = "0.3.4"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[features]
wasm-output-mode = [
    "elrond-wasm-node",
    "node-storage-wasm",
]

default = [
    "node-storage-default",
]

[dependencies]
node-storage-wasm = { package = "node-storage", path = "../node-storage", features = ["wasm-output-mode"], optional = true }
node-storage-default = { package = "node-storage", path = "../node-storage", optional = true }

elrond-wasm = "0.9.6"
elrond-wasm-derive = "0.9.6"
elrond-wasm-node = { version = "0.9.6", optional = true }

[dev-dependencies]
elrond-wasm-debug = "0.9.6"
