[workspace]
members = [
  "node-storage",
  "user-fund-storage",
  
  "auction-mock",
  "auction-mock/meta",
  "latest",
  "latest_full",
  "latest_full/meta",
  "latest_update",
  "latest_update/meta",
]
