[package]
name = "node-storage"
version = "0.4.0"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[dependencies.elrond-wasm]
version = "0.23.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.23.0"
