[package]
name = "delegation_latest"
version = "0.5.8"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[dependencies.node-storage]
path = "../node-storage"

[dependencies.user-fund-storage]
path = "../user-fund-storage"

[dependencies.elrond-wasm-module-dns]
version = "0.23.1"

[dependencies.elrond-wasm-module-features]
version = "0.23.1"

[dependencies.elrond-wasm-module-pause]
version = "0.23.1"

[dependencies.elrond-wasm]
version = "0.23.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.23.1"
