[package]
name = "delegation_latest"
version = "0.5.8"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"
[dependencies.node-storage]
path = "../node-storage"

[dependencies.user-fund-storage]
path = "../user-fund-storage"

[dependencies.elrond-wasm-modules]
version = "0.33.0"

[dependencies.elrond-wasm]
version = "0.33.0"
[dev-dependencies.elrond-wasm-debug]
version = "0.33.0"
