[package]
name = "delegation-latest-update-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2018"
publish = false
[dependencies.delegation_latest_update]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
