[package]
name = "user-fund-storage"
version = "0.5.8"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"
[dependencies.elrond-wasm]
version = "0.33.0"
[dev-dependencies.elrond-wasm-debug]
version = "0.33.0"
